#ifndef SPDIF_TX_H
#define SPDIF_TX_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* CN8 S/PDIF output. The transmitter consumes the same interleaved stereo PCM
 * buffer as SAI1, using its own SAI2 DMA stream. */
uint8_t SPDIF_TX_Init(uint32_t sample_rate, uint16_t bits_per_sample);
void SPDIF_TX_DeInit(void);
uint8_t SPDIF_TX_Start(const void *pcm, uint32_t bytes);
void SPDIF_TX_Stop(void);
void SPDIF_TX_Pause(void);
void SPDIF_TX_Resume(void);
uint8_t SPDIF_TX_IsRunning(void);
void SPDIF_TX_DmaIRQHandler(void);

/* Build one 32-bit SAI S/PDIF data-register word. Audio occupies bits 23:0,
 * V/U/C occupy bits 24/25/26, and parity/preamble are generated by hardware. */
uint32_t SPDIF_TX_EncodeSample(int32_t sample, uint16_t bits_per_sample,
                               uint32_t sample_rate,
                               uint32_t channel_status_frame);

#ifdef __cplusplus
}
#endif

#endif /* SPDIF_TX_H */
